import {
	buy,
	buy1,
	buy2,
	buy3,
	buy4,
	buy5,
	buy6,
	buy7,
	buy8,
	buy9,
	user,
} from 'assets/images';
const BuyData = [
	{
		id: 1,
		image: buy,
		title: 'Nairobi Estate',
		price: 'Ksh.5 Million',
		bed: '2',
		bath: '2',
		sqf: '700',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 2,
		image: buy1,
		title: 'Thika Estate',
		price: 'Ksh.2 Million',
		bed: '4',
		bath: '4',
		sqf: '2,000',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 3,
		image: buy2,
		title: 'Kisumu Estate',
		price: 'Ksh.10 Million',
		bed: '4',
		bath: '2',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 4,
		image: buy3,
		title: 'Eldoret Estate',
		price: 'Ksh.1 Million',
		bed: '2',
		bath: '1',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 5,
		image: buy4,
		title: 'Malindi Estate',
		price: 'Ksh.3 Million',
		bed: '1',
		bath: '1',
		sqf: '500',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 6,
		image: buy5,
		title: 'Kikuyu Estate',
		price: 'Ksh.1.5 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 7,
		image: buy6,
		title: 'Kajiado Estate',
		price: 'Ksh.25 Million',
		bed: '4',
		bath: '2',
		sqf: '1,800',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 8,
		image: buy7,
		title: 'Kwale Estate',
		price: 'Ksh.5 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 9,
		image: buy8,
		title: 'Machakos Estate',
		price: 'Ksh.15 Million',
		bed: '4',
		bath: '4',
		sqf: '2,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 10,
		image: buy9,
		title: 'Nyeri Estate',
		price: 'Ksh.13 Million',
		bed: '4',
		bath: '4',
		sqf: '1,000',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
];

export default BuyData;
