import {
	real,
	real1,
	real2,
	real3,
	real4,
	real5,
	real6,
	real7,
	real8,
	real9,
	user,
} from 'assets/images';
const RentData = [
	{
		id: 1,
		image: real,
		title: 'Runda Paradise Estate',
		price: 'Ksh.130,000',
		bed: '5',
		bath: '5',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 2,
		image: real1,
		title: 'Kencom Estate',
		price: 'Ksh.200,000',
		bed: '4',
		bath: '4',
		sqf: '1,000',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 3,
		image: real2,
		title: 'Fourways Estate',
		price: 'Ksh.100,000',
		bed: '3',
		bath: '4',
		sqf: '1,800',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 4,
		image: real3,
		title: 'Runda Gardens Estate',
		price: 'Ksh.250,000',
		bed: '4',
		bath: '4',
		sqf: '800',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 5,
		image: real4,
		title: 'Ridgeways Estate',
		price: 'Ksh.80,000',
		bed: '6',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 6,
		image: real5,
		title: 'Muthithi Estate',
		price: 'Ksh.160,000',
		bed: '4',
		bath: '6',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 7,
		image: real9,
		title: 'Kitusuru Estate',
		price: 'Ksh.300,000',
		bed: '6',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 8,
		image: real7,
		title: 'Lavington Estate',
		price: 'Ksh.210,000',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 9,
		image: real6,
		title: 'Westlands Estate',
		price: 'Ksh.60,000',
		bed: '5',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 10,
		image: real8,
		title: 'Karen Estate',
		price: 'Ksh.330,000',
		bed: '3',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
];

export default RentData;
