import {
	sell,
	sell1,
	sell2,
	sell3,
	sell4,
	sell5,
	sell6,
	sell7,
	sell8,
	sell9,
	user,
} from 'assets/images';
const SellData = [
	{
		id: 1,
		image: sell,
		title: 'Mombasa Estate',
		price: 'Ksh.25 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 2,
		image: sell1,
		title: 'Nakuru Estate',
		price: 'Ksh.17 Million',
		bed: '4',
		bath: '3',
		sqf: '1,400',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 3,
		image: sell2,
		title: 'Ngong Estate',
		price: 'Ksh.30 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 4,
		image: sell3,
		title: 'Nanyuki Estate',
		price: 'Ksh.45 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 5,
		image: sell4,
		title: 'Athi River Estate',
		price: 'Ksh.23 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 6,
		image: sell5,
		title: 'Naivasha Estate',
		price: 'Ksh.45 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 7,
		image: sell6,
		title: 'Juja Estate',
		price: 'Ksh.15 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 8,
		image: sell7,
		title: 'Lamu Estate',
		price: 'Ksh.5 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 9,
		image: sell8,
		title: 'Nyandarua Estate',
		price: 'Ksh.70 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 10,
		image: sell9,
		title: 'Ruiru Estate',
		price: 'Ksh.52 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
];

export default SellData;
