import {
	buy2,
	buy6,
	buy9,
	real4,
	real6,
	sell2,
	sell3,
	sell4,
	user,
} from 'assets/images';
const SellData = [
	{
		id: 1,
		image: real4,
		title: 'Ridgeways Estate',
		price: 'Ksh.80,000',
		bed: '6',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 2,
		image: real6,
		title: 'Westlands Estate',
		price: 'Ksh.60,000',
		bed: '5',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 3,
		image: sell2,
		title: 'Ngong Estate',
		price: 'Ksh.30 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 4,
		image: sell3,
		title: 'Nanyuki Estate',
		price: 'Ksh.45 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 5,
		image: buy9,
		title: 'Nyeri Estate',
		price: 'Ksh.13 Million',
		bed: '4',
		bath: '4',
		sqf: '1,000',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 6,
		image: buy6,
		title: 'Kajiado Estate',
		price: 'Ksh.25 Million',
		bed: '4',
		bath: '2',
		sqf: '1,800',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 7,
		image: buy2,
		title: 'Kisumu Estate',
		price: 'Ksh.10 Million',
		bed: '4',
		bath: '2',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
	{
		id: 8,
		image: sell4,
		title: 'Athi River Estate',
		price: 'Ksh.23 Million',
		bed: '4',
		bath: '4',
		sqf: '1,200',
		Amenities1: 'Backup Generator',
		Amenities2: 'Kids Playing Area',
		Amenities3: '24 Hours Security',
		Amenities4: 'Fully Equipped Gym',
		Amenities5: 'Borehole',
		Amenities6: 'CCTV',
		Amenities7: '24 Hours Security',
		Amenities8: 'Gated Community',
		Amenities9: 'Secured Gates',
		Amenities10: 'Video Intercom',
		Amenities11: 'Internet Ready',
		Amenities12: 'Indoor Games Room',
		Amenities13: 'Electric Fence',
		Amenities14: 'Elevator',
		Amenities15: 'BBQ Area',
		Amenities16: 'Heated Swimming Pool',
		Amenities17: 'Cable TV Ready',
		Amenities18: 'Controlled Parking',
		AgentImage: user,
		AgentName: 'Jane Doe',
		AgentNumber: '0754000000',
		AgentEmail: 'agentemail@gmail.com',
		description:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Etvoluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et voluptas inventore ad officia vel beatae delectus, reiciendis voluptatem porro repellat, aspernatur suscipit assumenda sit labore corrupti eveniet quis eum dolore?',
	},
];

export default SellData;
